spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:memdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
